import math

DOOM_RES = DOOM_W, DOOM_H = 360, 190

SCALE = 4.0
WIN_RES = WIN_W, WIN_H = int(DOOM_W * SCALE), int(DOOM_H * SCALE)
CEN_W, CEN_W = WIN_W // 2, WIN_H // 2

FOV = 90.0
H_FOV = FOV / 2

PLAYER_SPEED = 0.3
PLAYER_ROT_SPEED = 0.12